
@startmindmap
* 起
    * 大箱１．風俗嬢だった私が憧れのアイドルと付き合えたのに、どうしてこうなってしまったんだろうと後悔する最初のヒキ
        * つかみ
            * 風俗嬢だった私の前に憧れのアイドルが現れて、まるで王子様に拾われたシンデレラみたいな気分だった。
            * そんな夢のような時間がずっと続くって思ってた。
            * なのに、どうして私は今こうなっているんだろう
                * ODをにおわせる錠剤の殻を描写
                * 伏線に使う、思い出のアイテムを描写
    * 大箱2．風俗店で茉莉と晃人が出会い、相性の良さからお互いを運命のように感じる
        * 中箱１．茉莉の日常と推しへの執着
            * 昼職はあたしに向いていなかった
                * 共同作業では能力の低いものを虐げていいというルールがある
                * disれdisれ
                * 「ぶりっこしたら生きてこれたんでしょ」
                * だから、私は今おっさんのちんぽを舐めている
            * あえぐ演技のセリフ
            * おっさんの独りよがりなテクニックアピール
            * 客のキモい発言、キモい顔が見てられなくて、ヨガってるふりして、目を閉じ想像の世界に入る茉莉
            * この場をしのぐために「もし性交の相手が晃人だったら」の妄想をする
            * 客を晃人に見立てて、甘い発言を繰り返す。
            * 客が射精して、茉莉が目を開く
            * グロテスクなおっさん（現実に引き戻される）の、甘い発言可愛かったよ発言のきもい描写
            * 昔はシンデレラになりたかったみたいな回想
                * 「シンデレラみたいに、王子様に連れ出されたいです」いうてた小学生時代の回想
                * 「はじめては好きな人と」何て言ってた少女漫画みてた中学生の回想
            * 王子様（晃人）に助けられる理想と風俗嬢としておっさんの性処理に使われるを現実を比較し、虚無に浸る
            * そのまま惰性で待機室に戻る
            * 自分より惨めな存在がいないとやってられなくなる。
            * 自分勝手な茉莉が、売れていない老けている風俗嬢をターゲットにする
            * 心の中で、さんざん馬鹿にする。(のちの伏線)
            * 嫌なことは浄化、浄化って言いながら晃人のSNSに上がってる画像を漁る
            * この写真誰が撮ってるんだろーと、写真の目のところを拡大し、男であることを確認する。
            * ネトストを完了し、「今日も女との絡みなし」〈晃人のストイックで、ハニートラップへの恐怖を反映〉といつもの掲示板に報告する。
        * 中箱２．晃人が客として突然現れる
            * 「新しい指名入ったよ」のボーイの声がする
            * 休憩もろくになしでまたかよと舌打ち
            * 「新しい客が来る　→　金づる、しかしどんな客が来るのか、どんな事させられるかわからなくて嫌だの気持ちでためらう
            * 「そんなの逃げてやればいいじゃん、ちんこちょん切ればいいじゃん」と自分の中のわがままな部分を奮い立たせる
            * ドアを開けると、晃人がいて固まる
            * 晃人が固まった茉莉を見て、「もしかして、俺のこと知ってる？」とにらむ
            * 晃人の疑り深そうな顔にフォーカス
            * 逡巡：もしかして芸能人のかたですか？
            * 準備するふりをして、さりげなく鞄のグッズをとっさにしまう
            * 準備にあたふたして、不審におもわれていないかをちらちらみる
            * テキトーにした化粧が気になって、「あっ先シャワー浴びますね！」と言ってしまう（本来は一緒に浴びる）
            * 「あんた、客つくの初めて？」と冷たく言われる
            * 勘違いしてくれてありがとう、想いながら慣れてない設定でいく
            * 「俺も初めてだから、店も、女も」とうつむきながらいう
            * こころのなかで、初めての女になれるの！？と舞い上がってしまう
            * 「入ってきなよ」と言われ、シャワーへ
            * シャワーで茉莉、逡巡
            * 仕事だったことを思い出し、「一緒にはいりませんか？」→「は？」→「お体洗いますよ」→「そういうシステムなんだ」と晃人に声をかける
            * 躊躇いなく服を脱ぐ晃人
            * 推しの裸を見るってこと！？ってなって、目を隠してしまう
            * 自分が裸なのに気づいて、急いでタオルで体をまく
            * 何も言わず、裸で茉莉に背を向ける晃人
            * 普通の客の前では、「身体を密着させてアピールする」が簡単にできるのに、かたまって何もできなくなる自分に葛藤
                * こんなんならせっかくアイドルに来てもらったのに喜んでもらえないって泣いちゃう
            * 「お背中流しますね」と恐る恐る背中に触れる
            * 振れた時に、ビクンと晃人の肩が震えて、「触れんな」と晃人が言ってしまう
            * 驚く茉莉、「ごめんなさい」と首を垂れる晃人
            * それで、晃人が自分で体を洗い出す
            * 気圧されるまま、シャワー室を出ていく茉莉
            * 「もしかりに、俺の名前がわかっても、俺がここに来たことは絶対にいわないで」とシャワー室から声がする
            * 色々考えながら、「もちろんです！」と茉莉は答える
            * 「ありがとう、お金はいくらでもはらうからさ」と心細そうな声がシャワー室から聞こえる
            * 出てきたころには、１時間のタイマーがなってしまう
            * シャワーに時間かけすぎたからだ、と茉莉が焦る
            * 「ごめんなさい、何もできないまま時間かかってしまって、もちろん最後まで」と茉莉がいいかける。
            * 晃人は「あんたの時間を奪うことはできない」と冷淡に切り捨てる。お金を突き付けて出ていこうとする。
            * 「でも、これじゃあせっかく来られたのに」と彼の腕を掴もうとすると、その手をはねのけられる
            * 「俺とあんたはあくまで客と嬢だ、それ以下でもそれ以上でもない。だから、金と時間で割り切れなきゃなんない。いや、割り切れるからこそ俺はこの店に来たんだ」
            * 困る茉莉
            * 「でもその理屈で言うと、私は嬢としてまた来てほしいんです。だからあなたによろこんでほしいんです」
            * 小さく、「お人よしがすぎるだろ」と吐き捨てて、茉莉の方に戻りハグをする
            * そのまま茉莉に晃人がキスをする
            * 「これで、いいだろ」と恥ずかしそうに部屋を出る晃人
            * 推しのキスをもらえて呆然とする茉莉
        * 中箱３．茉莉、嬉しくなって雫に電話で話す
            * 役割
                * 雫のキャラクターの自然な紹介
                * 晃人に対する謎の提示
                * 茉莉の幻想と、客観視した雫の感想を交互に描写する
                    * 認知の歪みと、晃人の内情を示唆
            * 私はうれしい時は親友の雫に鬼電するのだ、的な字の文で雫を紹介
            * 「それでね、」から始まるまとまりもない語り
                * すごく緊張して、普通に接せなかったこと
                * 気づいたら時間たってたこと
                * 「君の時間がは奪えないよ」を美化
                * それでキス
            * めっちゃよかったじゃん、でもそういう話私以外にしないほうがいいよとゲンチアナする
            * え？何でと茉莉が聞き返す
            * 雫が、だってわからないことだらけじゃない？と、以下の謎を茉莉に掘り返す
                * なぜアイドルなのに風俗店に来るのか　→　秘密厳守の店だから意外と芸能人は来るよ
                * なぜ、触れられることや自己開示をかたくなに拒むのか
            * 「そっか、私晃人くんのこと全然見れてなかったかも」茉莉の示唆
            * それに、「裏はどんな人かわからないよ」と震えた声で伏線を張る
            * えっ？の茉莉
                * 晃人君は私の王子様なの、そんなわけないじゃんと内心憤る
                * （伏線）雫は、男性で嫌な思いをしているから、それで考えすぎてるんだと思う
            * だから、困ったら私にだけ相談してね、忙しくても絶対相談にのるから
            * 「大好き～愛してる」の茉莉
            * やめてよ、（私の気持ちを知りもしないで）
            * 茉莉「また来てくれるかなあ」、雫「きたらいいね」
        * 中箱４．晃人が、だんだん茉莉に心を許していく
            * 役割
                * 晃人行動の洞察
                * 晃人が茉莉にはまっていくのを描写
            * （地の文）晃人が常連になってくれて、茉莉が舞い上がる
            * 茉莉が晃人に触れようとして拒絶しようと反射的にするのを描写
            * 毎回、行為を断って帰る晃人に茉莉が不思議に思う
            * 性行為自体には興味がない、怖いと語る晃人
                * Q.じゃあ何でうちきたの？
                * A.店の口の堅さ
            * 正直、行為よりもハグがしたいと語る晃人
                * その方がうれしい！イチャイチャのほうが好きなんだよね
                * 「そういうの憧れる、怖いから」と語る晃人
                * 「じゃあ、私があなたの理想の彼女になってあげる」
                * ハグで思いっきり茉莉が甘やかす
            * 本当は興味ないんじゃなくて、怖いんだと語る晃人
                * できなくてもいいから、してみると誘う茉莉
                * いざ、しようという所で涙を流して、できない、ごめんなさいと語る晃人
                * それを優しく抱きしめる茉莉
            * 事後、リードしてる感だしつつも、「本当の恋人みたいにさ、LINEも交換しない」と恐る恐る誘う茉莉
            * 無言でQRを見せて、「これで満足したか？営業ご苦労さま」と吐き捨てて、さっていく晃人
            * 心の中で舞い上がる茉莉
            * 晃人を追いかけて「また来てね！」と手を振る茉莉
            * 「外で俺に話しかけないでくれ」と憤り、来なくなった晃人
        * 中箱５．茉莉が晃人に告白をし、晃人がアイドルであることを明かす
            * 茉莉がダメ元で、プライベートであってくださいのLINEを送る
            * ３週間後、晃人が会う場所を指定して返信をする
                * 細かすぎる指定を不審に思うも、恋の盲目は止められない
            * あったときに、唐突に茉莉が告白する
            * いいけど、関係性を秘密にしてほしいんだと語る晃人
                * 外で会わない
                * 仕事場には来ないで
            * 晃人が、勇気を振り絞ってアイドルであることを自分から話す
            * 晃人が過去の不自然な言動に関して謝る
                * ハニトラへの恐怖とか、もろもろを全部口にする
            * 茉莉が、関係性を隠し通すことを決意する。
                * 簡単に、口の堅い女に生まれかわりますって地の文で書く程度
        * 中箱６．茉莉が晃人に好かれるように努力し、晃人が茉莉に依存していく１
            * 練習おわりに、LINEがぎこちなく帰ってくるだけの恋人生活を打破するために、茉莉がデートに誘う
            * 晃人から、外では会えないという、そっけない返事が返ってくる。
            * 茉莉が勇気を出しておうちデートに誘う。
            * おうちデートに誘われても気まずいまま、固まってしまいる晃人を描く
            * 茉莉が焦ってパニックになって、私にお店の時のように性的に接待しようとする
            * 「これじゃあ客の時と変わらないじゃないか」と晃人がいう
            * 「でも私にはそれくらいしかできなくて」と茉莉が言う
            * 「僕気を使われるの嫌いなんだ、帰るよ」と晃人が言う
            * 「どうしても好きなの！あなたがいてくれないといやだから、わけわかんなくなってこうしたの！」と泣きながら茉莉が言う
            * 内心うれしいのを隠しながら、ドアの前で佇む晃人
            * 「だいたい、ファンでもないのに俺みたいなやつ、何で好きになんだよ」と問う晃人
            * 言葉に詰まる茉莉
            * 「結局、顔で好きになって、中身は思ってたんと違ったってお前も突き放すんだろ、簡単に裏切るんだろ」と疑心暗鬼を見せる晃人
            * 「そんなわけない」と叫ぶ茉莉
            * 「確かに愛情に理由なんてないって不安になるのもわかる、晃人君が今までどんな辛いおもいをしてきたかも知らない、でも私は絶対どんな晃人君だって愛する自信がある、晃人君の心の闇だって、絶対あかりをともして見せる、だから、絶対に来週も、また次の週も来て、証明してみせるから」と言い切り、ドアを閉める。
            * あっけにとられる晃人
* 承
    * 大箱１．晃人が兄に関する秘密を茉莉に暴露し、兄に関する晃人の復讐心が表面化して、茉莉が困る
        * 中箱1．晃人が茉莉に兄の秘密を打ち明ける
            * 晃人が茉莉の家にやってくる
            * 茉莉は「先週は変な啖呵を切ってごめんね」と話そうとする
            * それを遮って晃人が、「いいや、俺も心の闇をちゃんと茉莉にさらす、茉莉にだけね」と言って秘密の開示を始める
            * まって、と茉莉が言うも晃人は止まらず、「俺の兄は天城陽翔なんだ」と語る
        * 中箱2．晃人視点で描かれる陽翔の理想像
            * 幼少期のあきとのプライドの高さを描く
            * あきとの他の馬鹿な生徒へのモラハラを描く
            * あきとがいじめられるシーン
            * はるとはあきとの相談に真剣にのって、辛いところを受け入れてくれた
            * はるとはいじめっ子とまず仲良くなる
            * いじめっ子の人気者になって
            * いじめっ子をちゃんと説得して
            * いじめっ子全員が素直に誤りに来る
            * あきとの機嫌が治ったところを見計らって、あきとの嫌がられる言動を論理的に示した。
            * はるとが人間的に優れていたところを強調
            * そんな誰からも好かれる兄さんがアイドルとして登り詰めるのは当然のことだった
        * 中箱3．陽翔のハニートラップによる転落（晃人の視点）
            * 久しぶりに兄が家に帰ってきて、喜ぶあきと
            * 俺、モデル雑誌にのったんだぜと、あきとにじまんするはると
            * 本屋さんに入っていく
            * 一緒に本屋さんに入っていく
            * 大見出しで、未成年に手を出すあまきはると、があり、これをはるとがびっくりして手に取る
            * 震えて、雑誌をおとすはると
            * 何読んでんの？と本を拾うあきと
            * ヒソヒソ声が周りから聞こえてくる
            * とんでもなく露悪的に書かれた雑誌を見て驚愕する
            * 涙を堪えながら走って家に帰るはるとをあきとがおいかける
            * 「信じてくれ、おれこんなことしていないんだ」と泣きながら訴えるはると
            * 鳴り響く携帯を無視する兄
            * （詳細はシーンで）
            * SNSを眺めてはやつれる兄
            * 個人情報がバレていき、やつれる兄
            * テレビニュースに流れてきてはチャンネルを変える家族
            * 部屋に引きこもる兄
            * 久しぶりに出かけるって言ったまま、ビルの屋上から飛び降り自殺した兄
        * 中箱4．晃人が復讐心の誓いを立てる
            * 自分に向けた兄の遺書を読んだ弟
            * あれはハニートラップだったんだ、と驚き憤慨するあきと
            * 兄の目標リストみたいなのを見て、僕がお兄ちゃんの代わりになってやるからなとかたる
            * そして、真実を白日の下にさらしてやる
            * そのために作ったクロミノートを見せる晃人
            * 個人情報を執拗に追いかけるファンに復讐心を見せる晃人
            * 復讐の日までは絶対に兄の弟であることがバレてはならないというあきと
        * 中箱5．晃人の復讐心が茉莉の不安をさらに煽る
            * 晃人が文春殺すと言いながら腕立て伏せしているところをみてしまう
            * 今までの掲示板の記録を消さなきゃと焦る茉莉
    * 大箱２．茉莉の掲示板投稿がバレて、晃人が困る
        * 中箱1．茉莉のPCの中身を晃人が偶然覗き見てしまう（茉莉がファンだったのがバレる）
            * 晃人がうちに来ない予定の日に、焦ってすぐに掲示板投稿を消し続ける茉莉
            * 茉莉トイレに行く
            * しかし、晃人が仕事早上がりで茉莉の家に帰ってくる
            * 晃人に関してストーカーするような投稿をしていたのをみてしまう
        * 中箱3．晃人が茉莉を追及する
            * このままじゃ、お前のこと信用できないんだけど、と晃人が淡々と追い詰める
            * どれだけ俺が苦しい思いをしてきたかを語る晃人
            * 今の記事じゃないし、変わろうとしているの　と訴求する茉莉
            * 晃人兄に関することまではバレてない、と安堵する茉莉
            * 晃人がPCのログイン情報を開示するように要求
            * 晃人がいないうちに茉莉が焦って、過去の兄に関する閲覧履歴を消す
            * 晃人がハッキングした茉莉のPCを操作記録をみて、過去に兄をdisってたスレを立ててた事を発覚する
            * 晃人が泣きながら怒鳴りつける
            * 茉莉は晃人に振られたと思って逃げ出してしまう
        * 中箱3．茉莉が、雫の家に逃げ込み、恋愛相談をする
            * 茉莉がドアを叩きながら雫の名前を叫ぶ。
                * 息が上がり、焦りに満ちた声で雫の名前を呼ぶ。
            * 雫が驚きながら茉莉を迎え入れる。
                * 茉莉の様子を見て、何があったのかと心配しつつも冷静に対応する。
            * 茉莉が部屋に飛び込み、その場で崩れるように座り込む。
                * 手で顔を覆い、声を震わせながら泣き出す。
            * 雫が茉莉に毛布を掛けて落ち着かせようとする。
                * 温かい飲み物を差し出し、そっと言葉をかける。
            * 茉莉が「私、もう無理……」と弱音を漏らす。
                * これまでの感情が堰を切ったように溢れ出す。
            * 雫が静かに茉莉の話を聞き始める。
                * 無理に言葉を挟まず、茉莉が話しやすい空気を作る。
            * 茉莉が晃人との喧嘩の内容を断片的に話す。（兄の話は話さないようにする、あ、これ秘密だったとか言って）
                * 混乱していて話が前後しながらも後悔をに口にする。
            * 雫が冷静に「大丈夫、少しずつ話して」と促す。
            * 茉莉が「どうしたらいいかわからない」と繰り返す。
            * 雫が「今日はいっぱい泣いて、寝ちゃおう」と促す
        * 中箱3．翌朝、晃人が雫の家にやってきて、もうお前なしでは生きれないんだと泣きながら伝える
            * 晃人のセリフの要約「俺は兄さんを侮辱した茉莉のことは一生許しはしない。それに元々悪質なファンだった茉莉なんて恋人にしておくには危険すぎるってわかってる。だけど、茉莉はいってくれたよな、どんな俺だって受け入れてくれるって。あの言葉が忘れられないんだよ。それにどうせ別れたって、俺の秘密がばらされるリスクがあがるだけだ。だから、俺が嫌なことはしない茉莉に代わって、それでうちに戻ってきてくれないか、いや戻って来てくれ、もう一人で生きるのは嫌なんだ、茉莉がいないと生きていけないんだ！」
            * 晃人と茉莉が涙して抱き合う
            * 何度も謝る茉莉
            * 雫が寂しい気持ちを隠しながらも、二人を応援する
    * 大箱３．水島　雫がレイプ事件の全貌をSNSに告発して、茉莉と晃人が困る
        * 中箱1．雫が茉莉に過去のトラウマに関して相談する
            * 雫がLINEで「茉莉に相談があるんだけど、～～の夜あいてる」って相談を持ち掛ける
            * 自分から相談をすることのなかった雫に驚き、茉莉は二つ返事で予定をあける
            * 雫の家で会う二人、雫がなかなか話を切り出せず、茉莉が「もしかしてまた男性関係で怖い思いしたの？」と尋ねる
            * 「違うの、私も茉莉の前で話せてなかった、心の闇があるの」
        * 中箱2．雫がされたことを話す
            * 雫がいきなり服・ブラジャーを脱ぐ
            * 胸の縫い跡を茉莉に見せる
            * これ、私嚙みちぎられたの、小学生の時、業界の人間にね
            * レイプシーンの詳細を茉莉に伝える
            * 私はベッドに戻るたびに、男の人と話すたびにあの日のことを思い出すの
            * この記憶にけりをつけたいの
            * あの時幼くて何も言えなかった私を救って、この記憶とおさらばしたいの
            * だから、私SNSでされたこと全部いうの。それで、全部終わらせるの
            * でもやっぱり怖いの、色んな人に叩かれるとか、
            * だから、茉莉にあと一歩踏み出す勇気を応援してほしいの
            * ねえ、私あいつに復讐しても、いいかなあ？と泣きながら茉莉に問う
            * わかった。じゃあ、一緒にSNSで告発しようと茉莉が言う。
            * 茉莉ちゃん、大好きと泣きながら雫が抱き着く
        * 中箱3．雫のSNS告発の始まり
        * 中箱4．晃人の兄への理想の崩壊
        * 中箱5．茉莉の晃人への幻想の崩壊
        * 中箱6．茉莉の雫への思い
        * 中箱7．晃人の無力感と孤立
        * 中箱8．茉莉の晃人への葛藤
        * 中箱9．雫のためらい
    * 大箱４．晃人が雫を止めるように惨めに縋ってきて、茉莉が困る
        * 中箱1．晃人が茉莉に助けを求め、茉莉が困惑する
        * 中箱2．茉莉が晃人と直接会い、彼の惨めな姿を目の当たりにする
        * 中箱3．茉莉が晃人の言葉を受け入れかねて葛藤する
    * 大箱５．これ以上大事にしないよう、茉莉が雫に強要して、雫が困る/強要せねばならなくて、茉莉が困る
        * 中箱1．茉莉が晃人の願いを受け入れるか葛藤する
        * 中箱2．茉莉が雫に接触し、説得を試みる
        * 中箱3．雫が茉莉の説得に困惑する
        * 中箱4．茉莉が雫の感情を操作する
        * 中箱5．雫が茉莉の言葉に応じるが内心に疑念が残る
        * 中箱6．茉莉と雫の関係に微妙な亀裂が生まれる
* 転
    * 大箱１．雫が晃人と茉莉の関係に気づき、雫が困る
        * 中箱1．茉莉が雫にカフェで恋愛相談をする
        * 中箱2．雫が茉莉のスマホを見て関係に気づく
        * 中箱3．雫が茉莉に裏切られたと感じて動揺する
        * 中箱4．雫が茉莉への怒りと哀しみを抱え込む
    * 大箱２．雫が週刊誌にリークして大炎上し、茉莉と晃人がとっても困り、破局する
        * 中箱．雫が週刊誌にリークする決意を固める
        * 中箱．週刊誌の記事が公開される
        * 中箱．SNSで炎上し、晃人が完全にアイドル活動へのやる気を失う
        * 中箱．強迫行動が酷くなって、アイドル活動をまったくしない晃人を描写
        * 中箱．晃人が、「俺のこと好きなんだったら、茉莉が勝手にストーカーしていただけです」って証言してくれるよね？と茉莉に言う
        * 中箱．苦悩を抱えながら、茉莉が晃人にとって都合が良いようにSNSで発言を繰り返す。
        * 中箱．浪費の激しい晃人のために、過酷なオプションをつけて接客する茉莉を描写。
        * 中箱．同僚が、晃人に関する自分の噂を流しているのを茉莉が聞くところを描写。
        * 中箱．茉莉、性病にかかる。
        * 中箱．茉莉に性病ゆえに、性行為を断られた晃人が、「きったねえ売女のために、俺のアイドル人生壊されたのかよ」と吐き捨てる
        * 中箱．耐えきれなくなった茉莉が、晃人に別れを切り出す
        * 中箱．晃人が、どんな自分でも愛してくれるっていったはずの茉莉に逆キレし、遂に暴力を振るってしまう
        * 中箱．泣きながら晃人の家から逃げ出す茉莉を描く
        * 中箱．泣きながら雫の家にやってきた茉莉が、「警察呼ぶよ！」と追い返されるシーンを描く
        * 中箱．こんなに酷い思いをしたのに、まだ好きで辛いと、漫画喫茶で泣く、茉莉の葛藤を描く
        * 中箱．週刊誌に切り取られる晃人の粗暴な言動
        * 中箱．完全に人生が終わったと思い、自殺未遂する晃人を描く
* 結
    * 大箱１．晃人が過去の恋愛について後悔しながら、苦しみながら生きていく様子が描かれる
        * 中箱．(回想)晃人のアイドル事務所解雇と無職の日々
        * 中箱．(回想)再起に向けて資格を取得し、社会人復帰するも噂により挫折するところを描く、
        * 中箱．(回想)理想化によって、晃人のヒモ生活が崩壊していくところを描く
        * 中箱．晃人が酒を飲みながら過去への執着を独白する
        * 中箱．サラ金が家にやって来て逃げだすのを描写
        * 中箱．兄の自殺現場での対話と絶望
    * 大箱２．茉莉が過去の恋愛について後悔しながら、苦しみながら生きていく様子が描かれる
        * 中箱．茉莉、風俗嬢として落ち目を感じ始める
        * 中箱．婚活を始めるが、相手を好きになれない
        * 中箱．プロポーズされるが受け入れられず、逃げ出してしまう
        * 中箱．汚い客の相手をしながら、自分の現状に絶望する
        * 中箱．晃人への執着や理想の高さに苦しみ続けることの独白
@endmindmap